version: '3.8'
services:

  clickhouse-01:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "1001:1001"
    container_name: clickhouse-01
    hostname: clickhouse-01
    volumes:
      - ./fs/volumes/clickhouse-01/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./fs/volumes/clickhouse-01/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./fs/volumes/clickhouse-01/etc/clickhouse-server/config.d/monitoring.xml:/etc/clickhouse-server/config.d/monitoring.xml
    ports:
      - "8123:8123"
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9363:9363"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03

  clickhouse-02:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "1001:1001"
    container_name: clickhouse-02
    hostname: clickhouse-02
    volumes:
      - ./fs/volumes/clickhouse-02/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./fs/volumes/clickhouse-02/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "127.0.0.1:8124:8123"
      - "127.0.0.1:9001:9000"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03

  clickhouse-03:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "1001:1001"
    container_name: clickhouse-03
    hostname: clickhouse-03
    volumes:
      - ./fs/volumes/clickhouse-03/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./fs/volumes/clickhouse-03/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "127.0.0.1:8125:8123"
      - "127.0.0.1:9002:9000"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03

  clickhouse-04:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "1001:1001"
    container_name: clickhouse-04
    hostname: clickhouse-04
    volumes:
      - ./fs/volumes/clickhouse-04/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./fs/volumes/clickhouse-04/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "127.0.0.1:8126:8123"
      - "127.0.0.1:9003:9000"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03


  clickhouse-keeper-01:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "1001:1001"
    container_name: clickhouse-keeper-01
    hostname: clickhouse-keeper-01
    tty: true
    volumes:
     - ./fs/volumes/clickhouse-keeper-01/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
     - ./fs/volumes/clickhouse-keeper-01/log:/var/log
     - ./fs/volumes/clickhouse-keeper-01/lib:/var/lib/clickhouse-keeper
    ports:
        - "127.0.0.1:9181:9181"

  clickhouse-keeper-02:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "1001:1001"
    container_name: clickhouse-keeper-02
    hostname: clickhouse-keeper-02
    tty: true
    volumes:
     - ./fs/volumes/clickhouse-keeper-02/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
     - ./fs/volumes/clickhouse-keeper-02/log:/var/log
     - ./fs/volumes/clickhouse-keeper-02/lib:/var/lib/clickhouse-keeper    
    ports:
        - "127.0.0.1:9182:9181"

  clickhouse-keeper-03:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "1001:1001"
    container_name: clickhouse-keeper-03
    hostname: clickhouse-keeper-03
    tty: true
    volumes:
     - ./fs/volumes/clickhouse-keeper-03/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
     - ./fs/volumes/clickhouse-keeper-03/log:/var/log
     - ./fs/volumes/clickhouse-keeper-03/lib:/var/lib/clickhouse-keeper    
    ports:
        - "127.0.0.1:9183:9181"


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - ./fs/volumes/prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - TERM=linux
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-polystat-panel
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_storage:/var/lib/grafana'


  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    container_name: kafka
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

  debezium:
    image: debezium/connect:1.4
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_PLUGIN_PATH: /kafka/connect/
    volumes:
      - ./assets/clickhouse-kafka-connect-v1.0.15.jar:/kafka/connect/debezium-connector-clickhouse/clickhouse-kafka-connect-v1.0.15.jar
    depends_on: [kafka]
    ports:
      - 8087:8083

  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.3
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081,http://localhost:8085
    ports:
      - 8085:8081
    depends_on: [zookeeper, kafka]
    
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9500:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    depends_on:
      - "kafka"

volumes:
  grafana_storage: {}
  prom_data: