global:
  scrape_interval: 1s # Set the global scrape interval to 15s. The default is 1 min.
  evaluation_interval: 1s # Set the global rule evaluation interval to 15s. The default is 1 min.
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: [localhost:9090]

- job_name: 'clickhouse'
  static_configs:
    - targets:
      - 'clickhouse-01:9363'